services:
  gerador-diagramas:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - app/.env
    volumes:
      - uploads:/app/static/uploads
    restart: unless-stopped

volumes:
  uploads:
